const ACTION_TYPES = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  SET_STEP: 'SET_STEP',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  CHANGE_THEME: 'CHANGE_THEME',

  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_ERROR: 'CREATE_USER_ERROR',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  WORKINING_USER_REQUEST: 'WORKINING_USER_REQUEST',
  WORKINING_USER_SUCCESS: 'WORKINING_USER_SUCCESS',
  WORKINING_USER_ERROR: 'WORKINING_USER_ERROR',
};

export default ACTION_TYPES;
